export const GET_DETAILS = "GET_DETAILS";
export const GET_DETAILSBYID = "GET_DETAILSBYID";
export const POST_DETAILS = "POST_DETAILS";
export const UPDATE_DETAILS = "UPDATE_DETAILS";
export const DELETE_DETAILS = "DELETE_DETAILS";
